name: Build All

on:
  workflow_dispatch:

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true 
  DOTNET_CLI_TELEMETRY_OPTOUT: 1 
  DOTNET_NOLOGO: 1

jobs:
  build-29:
    runs-on: windows-2022
    outputs:
      electron: ${{ steps.electron-version.outputs.electron }}
       
    name: build electron-29.0.0
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Electron 29
        uses: ./.github/actions/build-electron
        with:
          electron: 29
          os: ${{ runner.os }}

      - name: Electron version
        shell: bash
        id: electron-version
        run: echo "electron=29.4.6" >> $GITHUB_OUTPUT
    
      # - name: Setup env
      #   uses: ./.github/actions/setup-env
      #   with:
      #     electron: '${{ matrix.electron }}.0.0'
      #     os: ${{ runner.os }}
   
      # - name: install node-gyp
      #   run: npm i -g node-gyp

      # - name: Create release folder
      #   run: |
      #       mkdir "release\ia32\${{ matrix.electron }}.0.0"
      #       mkdir "release\x64\${{ matrix.electron }}.0.0"
      #       mkdir "release\arm64\${{ matrix.electron }}.0.0"

      # - name: Cache node-gyp
      #   uses: actions/cache@v4
      #   env:
      #     cache-name: cache-node-gyp
      #   with:
      #     path: ~\AppData\Local\node-gyp\Cache
      #     key: '${{ matrix.electron }}.0.0'

      # - name: Build ia32
      #   timeout-minutes: 30
      #   uses: ./.github/actions/build
      #   with:
      #     electron: ${{ matrix.electron }}
      #     arch: 'ia32'

      # - name: Build x64
      #   timeout-minutes: 30
      #   uses: ./.github/actions/build
      #   with:
      #     electron: ${{ matrix.electron }}
      #     arch: 'x64'

      # - name: Build arm64
      #   timeout-minutes: 30
      #   uses: ./.github/actions/build
      #   with:
      #     electron: ${{ matrix.electron }}
      #     arch: 'arm64'
    
      # - name: Upload artifacts
      #   uses: actions/upload-artifact@v4
      #   if: success()
      #   with:
      #     name: electron-edge-js-${{ matrix.electron }}.0.0
      #     path: |
      #       release


  test-29:
    strategy:
      matrix: 
       os: [windows-2022]
    runs-on: ${{ matrix.os }}
    needs: build-29

      # fail-fast: false

    name: test ${{ matrix.os }}-v ${{needs.build-29.outputs.electron}}
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test build
        uses: ./.github/actions/test-build
        with:
          electron: ${{ needs.build-29.outputs.electron }}
          os: ${{ matrix.os }}
  
    