name: Build

on:
  workflow_dispatch:
    inputs:
      build-version:
        description: 'Electron version to build'
        required: true
        default: '30'
        type: choice
        options:
        - 29
        - 30
        - 31
        - 32
        - 33
      # test-version:
      #   description: 'Electron version to test build'
      #   required: true
      #   default: '31.6.0'
      #   type: choice
      #   options:
      #   - 29.4.6
      #   - 30.5.1
      #   - 31.6.0

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true # required to setup CSC
  DOTNET_CLI_TELEMETRY_OPTOUT: 1 
  DOTNET_NOLOGO: 1

jobs:
  build:
    runs-on: ${{ matrix.os }}
    outputs:
      test-version: ${{ steps.electron-test-version.outputs.test-version }}
    strategy:
      # fail-fast: false
      matrix:
        os: [windows-2022]
       
    name: build ${{ matrix.os }}-v${{ inputs.build-version }}
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Resolve Electron version from major
        id: electron-test-version
        shell: bash
        run: |
            if [[ ${{ inputs.build-version }} == '29' ]]; then
              echo "test-version=29.4.6" >> $GITHUB_OUTPUT
            elif [[ ${{ inputs.build-version }} == '30' ]]; then
              echo "test-version=30.5.1" >> $GITHUB_OUTPUT
            elif [[ ${{ inputs.build-version }} == '31' ]]; then
              echo "test-version=31.7.2" >> $GITHUB_OUTPUT
            elif [[ ${{ inputs.build-version }} == '32' ]]; then
              echo "test-version=32.2.2" >> $GITHUB_OUTPUT
            elif [[ ${{ inputs.build-version }} == '33' ]]; then
              echo "test-version=33.0.2" >> $GITHUB_OUTPUT
            fi 

      - name: Setup env
        uses: ./.github/actions/setup-env
        with:
          electron: '${{ inputs.build-version }}.0.0'
          os: ${{ matrix.os }}
   
      - name: install node-gyp
        run: npm i -g node-gyp

      - name: Create release folder
        run: |
            mkdir "release\ia32\${{ inputs.build-version }}.0.0"
            mkdir "release\x64\${{ inputs.build-version }}.0.0"
            mkdir "release\arm64\${{ inputs.build-version }}.0.0"

      - name: Build ia32
        timeout-minutes: 30
        uses: ./.github/actions/build-ia32
        with:
          electron: ${{ inputs.build-version }}

      - name: Build x64
        timeout-minutes: 30
        uses: ./.github/actions/build-x64
        with:
          electron: ${{ inputs.build-version }}

      - name: Build arm64
        timeout-minutes: 30
        uses: ./.github/actions/build-arm64
        with:
          electron: ${{ inputs.build-version }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: electron-edge-js-${{ inputs.build-version }}.0.0
          path: |
            release

  test:
    runs-on: ${{ matrix.os }}
    needs: build
    strategy:
      matrix:
        os: [windows-2022]
      # fail-fast: false

    name: test ${{ matrix.os }}-v${{ needs.build.outputs.test-version }}
    steps:
      - name: Test build
        uses: ./.github/actions/test-build
        with:
          electron: ${{ needs.build.outputs.test-version }}
          os: ${{ matrix.os }}
  
    